version: "3.8"

services:
  referred_server:
    container_name: {{project_name}}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
    stdin_open: true
    tty: true
    ports:
      - '3001:3000'