#name: Build and Host Server
#
#on:
#  release:
#    types:
#      - published
#
#jobs:
#  deploy:
#    runs-on: self-hosted
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Deploy on Server
#        run: |
#          SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
#          SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
#          SUPABASE_JWT_SECRET=${{ secrets.SUPABASE_JWT_SECRET }} \
#          docker compose -f docker-compose-dev.yml up -d --build
#      - name: Prune dangling images
#        run: docker image prune -f